# -*- coding: utf-8 -*-
"""Gradient Boosting unmon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXbkh05Fwmvk6OQ1sdujLavlZZVzMOIG

# Prerequisite
"""

from google.colab import drive
drive.mount('/content/drive')

"""##이진분류"""

import pickle
with open("/content/drive/MyDrive/GitHub/global/mon2.pkl", 'rb') as fi: # Path to mon_standard.pkl in Colab
    df1 = pickle.load(fi)
print("Loading mon_df1_contiuous...")

import pickle
with open("/content/drive/MyDrive/GitHub/global/unmon2.pkl", 'rb') as fi: # Path to mon_standard.pkl in Colab
    df2 = pickle.load(fi)
print("Loading mon_df2_contiuous...")

df1['label'] = 1
df1.head()

df2.head()

import pandas as pd
import numpy as np

df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)
df_combined.head()

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X = df_combined[['burst_mean','burst_std', 'burst_var','total_income', 'total_outcome', 'packet_num', 'outgoing_ratio', 'incoming_ratio', 'duration','time_mean', 'time_var','size_mean','size_std','size_var','cumlative_std','cumlative_mean','cumlative_var','duration_per_packet']]
y = df_combined['label']

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Gradient Boosting 모델 생성 및 학습
model = GradientBoostingClassifier(learning_rate=0.01, n_estimators=100, random_state=42)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, confusion_matrix

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Accuracy를 퍼센트로 표시
accuracy_percent = accuracy * 100
print(f'Accuracy: {accuracy_percent:.2f}%')

# Precision
precision = precision_score(y_test, y_pred, average='micro')
print(f'Precision: {precision:.2f}')

# Recall
recall = recall_score(y_test, y_pred,average='macro' )
print(f'Recall: {recall:.2f}')


# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:\n', conf_matrix)

"""##다중분류"""

import pickle
with open("/content/drive/MyDrive/GitHub/global/mon2.pkl", 'rb') as fi: # Path to mon_standard.pkl in Colab
    df1 = pickle.load(fi)
print("Loading mon_df1_contiuous...")

import pickle
with open("/content/drive/MyDrive/GitHub/global/unmon2.pkl", 'rb') as fi: # Path to mon_standard.pkl in Colab
    df2 = pickle.load(fi)
print("Loading mon_df2_contiuous...")

import pandas as pd
import numpy as np

df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)
df_combined.head()

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X = df_combined[['burst_mean','burst_std', 'burst_var','total_income', 'total_outcome', 'packet_num', 'outgoing_ratio', 'incoming_ratio', 'duration','time_mean', 'time_var','size_mean','size_std','size_var','cumlative_std','cumlative_mean','cumlative_var','duration_per_packet']]
y = df_combined['label']

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Gradient Boosting 모델 생성 및 학습
model = GradientBoostingClassifier(learning_rate=0.1, n_estimators=50, random_state=42)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, confusion_matrix

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Accuracy를 퍼센트로 표시
accuracy_percent = accuracy * 100
print(f'Accuracy: {accuracy_percent:.2f}%')

# Precision
precision = precision_score(y_test, y_pred, average='micro')
print(f'Precision: {precision:.2f}')

# Recall
recall = recall_score(y_test, y_pred,average='macro' )
print(f'Recall: {recall:.2f}')


# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:\n', conf_matrix)